### ISSUE TITLE
Not an issue, just wanted to say THANKS.

### ISSUE THREAD

**Issue by cleverestx** [fitchmultz/chat-with-gpt#33]
I'm curious if you plan on maintaining this, adding stuff as time goes on, etc...?

**Comment by fitchmultz** [comment]
I plan to keep the models up to date and patch vulnerabilities. I've wanted to add support for saving prompt templates and other APIs but I am admittedly still learning this type of dev work. Happy to accept help and take requests though.

**Comment by cleverestx** [comment]
I think prompt templates are a great goal to have and do work on, and obviously keeping up vulnerability patching is probably the most important thing.

Honestly, most of my text chatting is done via text generation web UI and sillytavern;. A lot of fun character fictional stuff... especially since it can access my desktop video card for much better performance (being locally ran LLM stuff)..so I'm not sure how that could possibly tie into this solution, but if I can think of more chatGPT related enhancements, I'll start posting Ideas.

**Comment by fitchmultz** [comment]
Models have been updated by the way. Just wanted to give you a heads up.

**Comment by cleverestx** [comment]
Thank you!

**Comment by guybarnhartmagen** [comment]
👍
