### ISSUE TITLE
Error: SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by gogo9th** [fitchmultz/chat-with-gpt#37]
Hi,

I wonder how I can get around this error: 

```
:Desktop/chat-with-gpt$ sudo docker run -v $(pwd)/data:/app/data -p 3000:3000 ghcr.io/fitchmultz/chat-with-gpt:latest

> chat-with-gpt@0.2.3 start
> npx ts-node --logError src/index.ts

Configuring Passport.
[Error: SQLITE_CANTOPEN: unable to open database file] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
}

```

**Comment by gogo9th** [comment]
I manually ran the server by doing this:
```

cd app 
npm install
npm build
cd ../server
npm install
cp ../app/build public -r
npm run start

```
The server runs okay, but my API key does not work:

` **I'm sorry, I'm having trouble connecting to OpenAI (no response from the API). Please make sure you've entered your OpenAI API key correctly and try again.**
`

My API key works for OpenAI's official tutorial of using it in Python:

```
# export OPEN_AI_KEY="My Key"

from openai import OpenAI
client = OpenAI()

completion = client.chat.completions.create(
  model="gpt-4-turbo",
  messages=[
    {"role": "system", "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."},
    {"role": "user", "content": "Why are companies blocking ChatGPT?"}
  ]
)

print(completion.choices[0].message)

```

Maybe the API you are using is deprecated?

**Comment by fitchmultz** [comment]
Are you still having this issue? Everything is functioning on my end but I'll see what I can do. I updated the openai package this week.

**Comment by gogo9th** [comment]
You can ssh-log in and check:
root
qwerzxcvqwer

**Comment by gogo9th** [comment]
Sorry, my ip is 143.198.77.28. You can ssh here. 

I have the data directory, but still does not work..

**Comment by fitchmultz** [comment]
Run the following command in the `/root/chat-with-gpt` directory, and try running the container again. I think it has something to do with running the container as root but this should fix it for now. 

`sudo chmod -R 777 $(pwd)/data`

**Comment by gogo9th** [comment]
How it is working, thanks a lot. However, one small issue is that my network has a firewall and it blocks all OpenAI connections. But even if I run your docker on a remote VM and access the VM's website from my fire-walled domain, it blocks any responses from ChatGPT. Is it because the ChatGPT connections are created between my local machine and the remote server, not between the VM and the remote server? If so, is there any way I could enforce the connection to be routed through the VM's website?

**Comment by gogo9th** [comment]
Another question I have is that could you add the feature such that Latex math syntax is visually pretty-printed?

**Comment by fitchmultz** [comment]
Latex math was working at some point so I must have broken something when updating a package. Can you post a screenshot of an example where it is broken? That'll help me get it sorted out.

**Comment by gogo9th** [comment]
Here is the screenshot:

![image](https://github.com/fitchmultz/chat-with-gpt/assets/8513552/33f934ad-fe05-46a2-bf8d-ee3a36fa87a7)

Also, I wonder if you could add the feature of :

1. Changing the user's password
2. Keeping the screen to where it is while GPT is still printing the answer (instead of auto-scrolling down), because I cannot read what I am reading if it keeps scrolling down. 

Thanks.

**Comment by fitchmultz** [comment]
I've looked into the math formatting issue and can't seem to figure it out just yet.

In the settings panel, under UI, uncheck the auto scroll while generating a response option and the screen will stay in place while generating.
