### ISSUE TITLE
Error: SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by mrthevinh** [fitchmultz/chat-with-gpt#57]
```
> chat-with-gpt@0.2.3 start
> npx ts-node --logError src/index.ts

Configuring Passport.
[Error: SQLITE_CANTOPEN: unable to open database file] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
}
npm notice
```

**Comment by fitchmultz** [comment]
See this issue. https://github.com/fitchmultz/chat-with-gpt/issues/37

Which directory are you trying to start the container in? Which user are you logged in as?

I'd suggest running it from the /opt directory. Try the following commands:

# Create necessary directories and set appropriate permissions
sudo mkdir -p /opt/chat-with-gpt/data
sudo chown -R $(id -u):$(id -g) /opt/chat-with-gpt

# Change to the correct directory
cd /opt/chat-with-gpt

# Pull the latest image
docker pull ghcr.io/fitchmultz/chat-with-gpt:latest

# Run the container
docker run -v /opt/chat-with-gpt/data:/app/data -p 3000:3000 ghcr.io/fitchmultz/chat-with-gpt:latest
